unique_ids:
  assets:
    standard-page.html: GDNVVNWXZCIVVMDZ4ECWAOJRQMWHFBJF
    theme.css: GEYTEHATWYIBPJSLQJUZHPZKQITPJWEM
  forms:
    Form1: B6LQD6P3KXZVUNHU7SW3F4CZI2NNWRML
  modules: {}
  scripts: {}
  server_modules: {}
